title: Bruce Pagano
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.75
  brandStrength: 1
  rhythmicContrast: 0.5
  brandColors:
    - '#d2dcde'
    - '#2c2f34'
    - '#646f75'
    - '#85919d'
    - '#b0bac3'
  lightness: 0.875
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: Bruce Pagano
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.5382979
layout_spectrum: 0.1787234
